- hosts: all
  become: true
  roles:
   - role: commons

#- hosts: servidor_ha
#  become: true
#  roles:
#   - role: router

- hosts: servidores_web
  become: true
  roles:
   - role: nginx

- hosts: servidores_web
  become: true
  roles:
   - role: mariadb

- hosts: servidores_web
  become: true
  roles:
   - role: wordpress
